name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest

      - name: Log in to GitHub Container Registry with retry
        if: github.ref == 'refs/heads/main'
        run: |
          for i in 1 2 3; do
            echo "Attempting to log in to ghcr.io (Attempt $i)"
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin && break
            echo "Login failed. Retrying in 15 seconds..."
            sleep 15
          done
      - name: Build and Push Docker Image to GHCR
        if: github.ref == 'refs/heads/main' # Only push on main branch
        run: |
          VERSION=$(echo ${GITHUB_SHA} | cut -c1-7)
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/voicetranscript-service
          # Docker image tags must be lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
          docker build . --tag $IMAGE_ID:$VERSION --tag $IMAGE_ID:latest
          docker push $IMAGE_ID --all-tags
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Clone or pull the repository
            if [ -d "voicetranscript-service" ]; then
              cd voicetranscript-service
              git pull
            else
              git clone https://github.com/${{ github.repository }}.git voicetranscript-service
              cd voicetranscript-service
            fi
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd voicetranscript-service
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            sudo docker-compose -f docker-compose.prod.yml pull
            sudo docker-compose -f docker-compose.prod.yml up -d --build
