name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest
      - name: Build Docker image
        run: docker build -t voicetranscript-service .

      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/main' # Only push on main branch
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        if: github.ref == 'refs/heads/main' # Only push on main branch
        run: |
          VERSION=$(echo ${GITHUB_SHA} | cut -c1-7)
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/voicetranscript-service
          # Docker image tags must be lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
          docker build . --tag $IMAGE_ID:$VERSION --tag $IMAGE_ID:latest
          docker push $IMAGE_ID --all-tags

